### ISSUE TITLE
Better Usage Example and Explanation

### ISSUE THREAD

**Issue by mekeor** [shipshapecode/ember-drop#59]
Could you please elaboraate on the usage of this addon? Especially, I don't understand how to use the `targetSelector` property.

Let's assume we've got an Ember component, called `Foo`. It writes "Foo: ", followed some given text `someText` with a tooltip `someTip`. How would we do that?

I've been trying something as follows. Template:

```
Foo: <span class="foobar">{{someText}}</span>

{{ember-drop
  content=dropContent
  openOn='always'
  position='top center'
  targetSelector='.foobar'
}}
```
CoffeeScript file:
```
  dropContent: Ember.computed "value", ->
    [
      {
        classes: 'text-class',
        text: @get "someTip"
        type: 'div'
      }
    ]
```

**Comment by rwwagner90** [comment]
@mekeor I think the docs, coupled with looking at the dummy app https://github.com/shipshapecode/ember-drop/blob/master/tests/dummy/app/templates/application.hbs are fairly sufficient examples.

Could you elaborate on what exactly doesn't work for you, what errors you are seeing, etc?

**Comment by mekeor** [comment]
You are right. Maybe I'll make PR with a better usage description in the README anyway. Thanks. <3

**Comment by rwwagner90** [comment]
@mekeor PRs are always welcome. I think it's pretty clear, but I'd be glad to add more detail, if you submit a PR.
